storage:
  enabled: true
  storageClassName: "standard"
  requests: 128Mi

extraObjects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: dfly-password
  stringData:
    password: foobar

passwordFromSecret:
  enable: true
  existingSecret:
    name: dfly-password
    key: password
